# Generated by Django 6.0.6 on 2026-06-25 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='onboarding_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='preferred_work_hours',
            field=models.CharField(blank=True, choices=[('morning', 'Morning (6 AM – 12 PM)'), ('afternoon', 'Afternoon (12 PM – 6 PM)'), ('evening', 'Evening (6 PM – 12 AM)'), ('flexible', 'Flexible / No Preference')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='primary_goal',
            field=models.CharField(blank=True, choices=[('task_management', 'Task Management'), ('focus_time', 'Deep Focus & Flow'), ('habit_tracking', 'Habit Tracking'), ('scheduling', 'Smart Scheduling'), ('all', 'All of the Above')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='work_role',
            field=models.CharField(blank=True, choices=[('developer', 'Developer'), ('designer', 'Designer'), ('manager', 'Manager'), ('student', 'Student'), ('freelancer', 'Freelancer'), ('other', 'Other')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='daily_saved_hours',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='flow_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='flow_state_active',
            field=models.BooleanField(default=False),
        ),
    ]
