# Generated by Django 6.0.6 on 2026-06-28 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0003_task_completed_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='HabitEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('completed', models.BooleanField(default=False)),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='productivity.habit')),
            ],
            options={
                'ordering': ['date'],
                'indexes': [models.Index(fields=['habit', 'date'], name='productivit_habit_i_6586fa_idx')],
                'unique_together': {('habit', 'date')},
            },
        ),
    ]
